version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: superdima_3000
      POSTGRES_PASSWORD: Sh_lM_2110
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superdima3000"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq_server
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  # REST API
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: api
    container_name: app_api
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_NAME: api
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/app_database
      SPRING_DATASOURCE_USERNAME: superdima3000
      SPRING_DATASOURCE_PASSWORD: Sh_lM2110
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      JAVA_OPTS: "-Xms256m -Xmx512m"
      IMAGES_PATH: /opt/app/images
    volumes:
        - ./images:/opt/app/images
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app_network
    restart: always

  # Bot сервис
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: bot
    container_name: app_bot
    ports:
      - "8080:8082"
    environment:
      SPRING_APPLICATION_NAME: bot
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/app_database
      SPRING_DATASOURCE_USERNAME: superdima3000
      SPRING_DATASOURCE_PASSWORD: Sh_lM2110
      JAVA_OPTS: "-Xms256m -Xmx512m"
      IMAGES_PATH: /opt/app/images
    volumes:
      - ./images:/opt/app/images
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app_network
    restart: always

  # Node сервис
  node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: node
    container_name: app_node
    ports:
      - "8083:8082"
    environment:
      SPRING_APPLICATION_NAME: node
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/app_database
      SPRING_DATASOURCE_USERNAME: superdima3000
      SPRING_DATASOURCE_PASSWORD: Sh_lM2110
      JAVA_OPTS: "-Xms256m -Xmx512m"
      IMAGES_PATH: /opt/app/images
    volumes:
      - ./images:/opt/app/images
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app_network
    restart: always

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  app_network:
    driver: bridge
